### ISSUE TITLE
pod 失败，podfile写错了。

### ISSUE THREAD

**Issue by zuohuachen** [debugly/FFmpegTutorial#18]
`use_frameworks!

platform :osx, '10.11'

target 'FFmpegTutorial-macOS' do
  pod 'FFmpegTutorial',:path => '../../'
end

pre_install do |installer|
  puts `../../download-vendor.sh macos 0.10.1-230831144049-ijk`
end`

如上源文件只有一个打印puts，没执行 sh文件。把它改成厦门这样，就可以执行了。

`
pre_install do |installer|
  podfile_path = File.dirname(File.realpath(__FILE__))
  script_relative_path = "../../download-vendor.sh"
  script_full_path = File.expand_path(script_relative_path, podfile_path)
  system("sh #{script_full_path} ios 0.10.1-230831144049-ijk")
end

`

**Comment by debugly** [comment]
不是啊，这里使用了最简单的反引号方式 `cmd` 调用了 shell ，然后通过 puts 把执行日志打印出来。
你可以看下这个：https://stackoverflow.com/questions/2232/how-to-call-shell-commands-from-ruby
麻烦改回去再试试，看下具体原因。

**Comment by zuohuachen** [comment]
环境：
ruby 2.6.10p210 (2022-04-12 revision 67958) [universal.arm64e-darwin23]
pod --version 1.13.0

报错原因：（但如果改成正常引号，可以正常执行）

➜  FFmpegTutorial git:(master) ✗ pod install --project-directory=Example/MacOS
Analyzing dependencies
Downloading dependencies
[!] An error occurred while processing the pre-install hook of the Podfile.

No such file or directory - ../../download-vendor.sh

/Users/chenzuohua/Documents/GitHub/FFmpegTutorial/Example/MacOS/Podfile:10:in ``'
/Users/chenzuohua/Documents/GitHub/FFmpegTutorial/Example/MacOS/Podfile:10:in `block (2 levels) in from_ruby'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-core-1.13.0/lib/cocoapods-core/podfile.rb:162:in `pre_install!'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:958:in `run_podfile_pre_install_hook'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:946:in `block in run_podfile_pre_install_hooks'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/user_interface.rb:149:in `message'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:945:in `run_podfile_pre_install_hooks'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:259:in `block in download_dependencies'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:257:in `download_dependencies'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:163:in `install!'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/bin/pod:25:in `<main>'

**Comment by debugly** [comment]
优化了脚本，现在可以 pod install --project-directory=Example/MacOS 了。
